# fly.toml app configuration file generated for blog-node-app on 2023-05-19T19:35:36-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blog-node-app"
primary_region = "ewr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
